apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebs-csi-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebs-csi-controller
  template:
    metadata:
      labels:
        app: ebs-csi-controller
    spec:
      containers:
      - name: ebs-csi-controller
        image: amazon/aws-ebs-csi-driver:v1.4.0
        command:
        - /csi-driver
